title = "Nikola Selic — AI Research Engineer"
baseURL = "https://nikolaselic.com/"
languageCode = "en-us"
enableRobotsTXT = true
enableGitInfo = true
canonifyURLs = true

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.renderer]
      unsafe = true
