title = "Nikola Selic - Blog"
baseURL = 'https://nikolaselic.me'
languageCode = 'en-us'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 30
